<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Aevatar.GAgents.Basic</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.AutoMapper"/>
    </ItemGroup>

    <ItemGroup Condition="'$(UseLocalProjects)' != 'true'">
        <PackageReference Include="Aevatar.Core" />
        <PackageReference Include="Aevatar.Core.Abstractions" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseLocalProjects)' == 'true'">
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.Core.Abstractions\Aevatar.Core.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.Core\Aevatar.Core.csproj" />
    </ItemGroup>

</Project>
