<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.AutoMapper" />
        <PackageReference Include="Aevatar.Core" />
        <PackageReference Include="Aevatar.Core.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aevatar.GAgents.Basic\Aevatar.GAgents.Basic.csproj" />
    </ItemGroup>

</Project>
